version: 2
updates:

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "npm"
      - "dependabot"
    allow:
      - dependency-type: "direct"
    open-pull-requests-limit: 1
    rebase-strategy: "disabled"
    target-branch: "master"
