name: tests

on: [ push ]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      max-parallel: 2
      matrix:
        node: [ 10, 12, 14, 15 ]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Cache node_modules
        id: node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules
      - name: Install NPM Dependencies
        run: npm install --silent | cat
      - name: run tests
        run: npm test
