name: tests

on: [ push ]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      max-parallel: 2
      matrix:
        node: [ 14, 16, 18, 19 ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Cache node_modules
        id: node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules
      - name: Install NPM Dependencies
        run: npm install --silent | cat
      - name: run tests
        run: npm run test-unit
